### ISSUE TITLE
GitHub Authentication

### ISSUE THREAD

**Issue by JetJet13** [mathbookio/mathbook#4]
### Goal
In order to keep track of tutorials being submitted via the `Tutorial Builder`, we need some form of authentication to keep track of contributors and their submissions of tutorials. 

### Approach
We want to integrate with Github's Public API and use their authentication solution.

**branch:** `feature/github-auth`
### Todo's
- [x] Integrate with Github API
- [x] Setup Authentication through GitHub 
- [x] Build `Sign in with GitHub` Portal

**Comment by JetJet13** [comment]
👍
